# Deadline checker

In [7]:
# Assignment - 1

# TODO - While creating a task, ask user about the deadline

# Start date - Pick automatically from today's date
# Deadline 

# # to-DO

# 1. Task-1 | Days left  | Green-color
# 2. Task-2 | Days left  | Red-color
# 3. Task-3 | Days left  | Green-color
# 4. Task-4 | Days left  | Red-color

In [3]:
import pandas as pd
from datetime import datetime, timedelta
from termcolor import colored

# Get today's date
today = pd.to_datetime("today").normalize()

# Ask number of tasks
n = int(input("How many tasks do you want to create? "))

# Create empty DataFrame
df = pd.DataFrame(columns=["Task", "Start Date", "Deadline (days)", "Deadline Date", "Days Left", "Status"])

# Collect task info
for _ in range(n):
    task_name = input("Enter task name: ")
    deadline_days = int(input("Enter deadline in days: "))
    
    deadline_date = today + pd.Timedelta(days=deadline_days)
    days_left = (deadline_date - today).days
    status = "Green" if days_left > 5 else "Red"
    
    # Add to DataFrame
    df = pd.concat([df, pd.DataFrame([{
        "Task": task_name,
        "Start Date": today,
        "Deadline (days)": deadline_days,
        "Deadline Date": deadline_date,
        "Days Left": days_left,
        "Status": status
    }])], ignore_index=True)

# Display tasks with color
print("\n--- TASK LIST ---")
for idx, row in df.iterrows():
    line = f"{idx + 1}. {row['Task']} | Days left: {row['Days Left']}"
    color = 'green' if row['Status'] == 'Green' else 'red'
    print(colored(line, color))

C:\Users\nikunj.dhaka\AppData\Local\Temp\ipykernel_28536\2953237921.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([{

--- TASK LIST ---
1. sdcs | Days left: 2
2. cdsd | Days left: 9
3. ds fd fd | Days left: 6
4. ds vfvfsv | Days left: 2
5. dsv fvvfsv | Days left: 3
6. vdsvsvdds | Days left: 6
7. vsfsvsv | Days left: 10
8. avfdvvsv | Days left: 1
9. vafdvfdv | Days left: 6
10. vsvfvvds | Days left: 18

In [4]:
df.to_csv("task_list.csv", index=False)

In [5]:
df = pd.read_csv("task_list.csv")

In [6]:
df

         Task  Start Date  Deadline (days) Deadline Date  Days Left Status
0        sdcs  2025-07-09                2    2025-07-11          2    Red
1        cdsd  2025-07-09                9    2025-07-18          9  Green
2    ds fd fd  2025-07-09                6    2025-07-15          6  Green
3   ds vfvfsv  2025-07-09                2    2025-07-11          2    Red
4  dsv fvvfsv  2025-07-09                3    2025-07-12          3    Red
5   vdsvsvdds  2025-07-09                6    2025-07-15          6  Green
6     vsfsvsv  2025-07-09               10    2025-07-19         10  Green
7    avfdvvsv  2025-07-09                1    2025-07-10          1    Red
8    vafdvfdv  2025-07-09                6    2025-07-15          6  Green
9    vsvfvvds  2025-07-09               18    2025-07-27         18  Green